# Generated by Django 3.2.9 on 2022-02-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='content_2',
            field=models.TextField(blank=True),
        ),
    ]
